### ISSUE TITLE
Add formula to install packed-mn version for easier setup

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/homebrew-metanorma#53] opened 2020-07-05 17:50 UTC
Maybe a separate formula while we're still testing?

Since packed-mn is platform + architecture specific.

**Comment by ronaldtse** [comment] 2020-07-05 17:51
Lins with https://github.com/metanorma/packed-mn/pull/47

**Comment by ronaldtse** [comment] 2020-07-06 09:15
@CAMOBAP please check the Homebrew formula for Terraform, they are single binary with architecture specific, too.

**Comment by CAMOBAP** [comment] 2020-09-15 08:50
Closed as duplicate of https://github.com/metanorma/homebrew-metanorma/issues/57

**Closed by CAMOBAP** 2020-09-15 08:50 UTC
Labels: enhancement
